# netlify.toml

[build]
  # Specify the build command (no build step required for Node.js backend)
  functions="functions"

  # Set the publish directory (where your built files reside)
  publish = "/"

# Optional: Declare environment variables (if needed)
# [build.environment]
#   VARIABLE_NAME = "your-value"
#   ANOTHER_VARIABLE = "another-value"
